"CPP Module 00  ",                   " about 1 day ",             " 0 XP ",      " Recommended ",   " finished"
"CPP Module 01  ",                   " about 1 day ",             " 0 XP ",      " Recommended ",   " finished"
"CPP Module 02 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"CPP Module 03 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"CPP Module 04 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"CPP Module 05 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"CPP Module 06 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"CPP Module 07 ",                    " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Exam Rank 02  ",                    " about 7 hours ",           " 0 XP ",      " Recommended ",   " finished"
"Exam Rank 03  ",                    " about 7 hours ",           " 0 XP ",      " Recommended ",   " finished"
"Exam Rank 04 ",                     " about 7 hours ",           " 0 XP ",      " Forbidden ",     " Not registered"
"Exam Rank 05 ",                     " about 7 hours ",           " 0 XP ",      " Forbidden ",     " Not registered"
"Exam Rank 06 ",                     " about 7 hours ",           " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 00 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 01 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 02 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 03 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 04 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 05 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 06 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Old-CPP Module 07 ",                " about 1 day ",             " 0 XP ",      " Forbidden ",     " Not registered"
"Libft  ",                           " about 70 hours ",          " 462 XP ",    " Forbidden ",     " finished"
"netwhat  ",                         " about 28 hours ",          " 462 XP ",    " Forbidden ",     " finished"
"Born2beroot ",                      " about 40 hours ",          " 577 XP ",    " Recommended ",   " Not registered"
"ft_printf  ",                       " about 175 hours ",         " 882 XP ",    " Recommended ",   " finished"
"get_next_line  ",                   " about 70 hours ",          " 882 XP ",    " Recommended ",   " finished"
"libasm ",                           " about 70 hours ",          " 966 XP ",    " Forbidden ",     " in progress"
"FdF ",                              " about 60 hours ",          " 1000 XP ",   " Recommended ",   " Not registered"
"fract-ol ",                         " about 60 hours ",          " 1000 XP ",   " Recommended ",   " Not registered"
"so_long ",                          " about 60 hours ",          " 1000 XP ",   " Recommended ",   " Not registered"
"minitalk ",                         " about 50 hours ",          " 1142 XP ",   " Recommended ",   " Not registered"
"pipex ",                            " about 50 hours ",          " 1142 XP ",   " Recommended ",   " Not registered"
"ft_server  ",                       " about 84 hours ",          " 1722 XP ",   " Forbidden ",     " finished"
"push_swap  ",                       " about 60 hours ",          " 1855 XP ",   " Recommended ",   " finished"
"ft_services ",                      " about 210 hours ",         " 2002 XP ",   " Forbidden ",     " Not registered"
"dr-quine ",                         " about 2 days ",            " 2520 XP ",   " Forbidden ",     " Not registered"
"minishell  ",                       " about 210 hours ",         " 2814 XP ",   " Forbidden ",     " finished"
"NetPractice ",                      " about 7 days ",            " 3160 XP ",   " Forbidden ",     " Not registered"
"Old-Philosophers ",                 " about 3 days ",            " 3360 XP ",   " Forbidden ",     " Not registered"
"Philosophers  ",                    " about 70 hours ",          " 3360 XP ",   " Forbidden ",     " finished"
"avaj-launcher ",                    " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"camagru ",                          " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"computorv1 ",                       " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_ality ",                         " about 14 days ",           " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_hangouts ",                      " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_linear_regression ",             " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_linux ",                         " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_ls ",                            " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_ping ",                          " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_script ",                        " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_select ",                        " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"ft_traceroute ",                    " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"humangl ",                          " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"swifty-companion ",                 " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"cub3d ",                            " about 280 hours ",         " 5775 XP ",   " Forbidden ",     " Not registered"
"miniRT  ",                          " about 300 hours ",         " 5775 XP ",   " Forbidden ",     " finished"
"dslr ",                             " about 14 days ",           " 6000 XP ",   " Forbidden ",     " Not registered"
"ft_malcolm ",                       " about 7 days ",            " 6000 XP ",   " Forbidden ",     " Not registered"
"darkly ",                           " about 14 days ",           " 6300 XP ",   " Forbidden ",     " Not registered"
"ft_containers ",                    " about 140 hours ",         " 7245 XP ",   " Forbidden ",     " Not registered"
"42run ",                            " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"abstract-vm ",                      " about 21 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"cloud-1 ",                          " about 7 days ",            " 4200 XP ",   " Forbidden ",     " Not registered"
"computorv2 ",                       " about 21 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"expert-system ",                    " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"famine ",                           " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"ft_ssl_des ",                       " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"ft_ssl_md5 ",                       " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"ft_turing ",                        " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"h42n42 ",                           " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"in-the-shadows ",                   " about 21 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"krpsim ",                           " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"lem_in ",                           " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"lem-ipc ",                          " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"little-penguin-1 ",                 " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"malloc ",                           " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"matcha ",                           " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"matt-daemon ",                      " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"mod1 ",                             " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"multilayer-perceptron ",            " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"nibbler ",                          " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"nm-otool ",                         " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"n-puzzle ",                         " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine OCaml ",                    " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine PHP Symfony ",              " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine Python Django ",            " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine Ruby on Rails ",            " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine Swift iOS ",                " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"Piscine Unity ",                    " about 180 days ",          " 9450 XP ",   " Forbidden ",     " Not registered"
"process-and-memory ",               " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"rubik ",                            " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"scop ",                             " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"snow-crash ",                       " about 21 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"strace ",                           " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"swingy ",                           " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"taskmaster ",                       " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"total-perspective-vortex ",         " about 14 days ",           " 9450 XP ",   " Forbidden ",     " Not registered"
"woody-woodpacker ",                 " about 7 days ",            " 9450 XP ",   " Forbidden ",     " Not registered"
"CPP Module 08 ",                    " about 1 day ",             " 9660 XP ",   " Forbidden ",     " Not registered"
"Old-CPP Module 08 ",                " about 1 day ",             " 9660 XP ",   " Forbidden ",     " Not registered"
"Inception ",                        " about 210 hours ",         " 10042 XP ",  " Forbidden ",     " in progress"
"boot2root ",                        " about 7 days ",            " 11500 XP ",  " Forbidden ",     " Not registered"
"guimp ",                            " about 21 days ",           " 12600 XP ",  " Forbidden ",     " Not registered"
"42sh ",                             " about 42 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"drivers-and-interrupts ",           " about 14 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"durex ",                            " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"filesystem ",                       " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"fix-me ",                           " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"ft_nmap ",                          " about 7 days ",            " 15750 XP ",  " Forbidden ",     " Not registered"
"ft_ssl_rsa ",                       " about 7 days ",            " 15750 XP ",  " Forbidden ",     " Not registered"
"ft_vox ",                           " about 21 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"hypertube ",                        " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"kfs-1 ",                            " about 42 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"kfs-2 ",                            " about 42 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"kfs-8 ",                            " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"kfs-9 ",                            " about 35 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"particle-system ",                  " about 21 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"pestilence ",                       " about 28 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"red-tetris ",                       " about 21 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"shaderpixel ",                      " about 21 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"swifty-proteins ",                  " about 21 days ",           " 15750 XP ",  " Forbidden ",     " Not registered"
"userspace_digressions ",            " about 42 days ",           " 16800 XP ",  " Forbidden ",     " Not registered"
"corewar ",                          " about 28 days ",           " 17500 XP ",  " Forbidden ",     " Not registered"
"rt ",                               " about 42 days ",           " 20750 XP ",  " Forbidden ",     " Not registered"
"ft_irc ",                           " about 175 hours ",         " 21630 XP ",  " Forbidden ",     " Not registered"
"Old-IRC ",                          " about 175 hours ",         " 21630 XP ",  " Forbidden ",     " Not registered"
"webserv ",                          " about 210 hours ",         " 21630 XP ",  " Forbidden ",     " Not registered"
"xv ",                               " about 56 days ",           " 22000 XP ",  " Forbidden ",     " Not registered"
"ft_transcendence ",                 " about 245 hours ",         " 24360 XP ",  " Forbidden ",     " Not registered"
"ft_newton ",                        " about 14 days ",           " 24360 XP ",  " Forbidden ",     " Not registered"
"bomberman ",                        " about 28 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"gomoku ",                           " about 28 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"kfs-4 ",                            " about 28 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"kfs-6 ",                            " about 42 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"music-room ",                       " about 28 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"rainfall ",                         " about 28 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"zappy ",                            " about 42 days ",           " 25200 XP ",  " Forbidden ",     " Not registered"
"gbmu ",                             " about 60 days ",           " 31500 XP ",  " Forbidden ",     " Not registered"
"Open Project ",                     " about 180 days ",          " 31500 XP ",  " Forbidden ",     " Not registered"
"death ",                            " about 21 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"Electronique ",                     " about 7 hours ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"kfs-3 ",                            " about 42 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"kfs-5 ",                            " about 56 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"kfs-7 ",                            " about 90 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"kfs-x ",                            " about 56 hours ",          " 35700 XP ",  " Forbidden ",     " Not registered"
"override ",                         " about 28 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
"war ",                              " about 28 days ",           " 35700 XP ",  " Forbidden ",     " Not registered"
